# Generated by Django 6.0.2 on 2026-02-25 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_cliente_logotipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClausulaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('financeiro', 'Financeiro'), ('sla', 'SLA'), ('tecnica', 'Técnica'), ('lgpd', 'LGPD'), ('penalidade', 'Penalidade'), ('rescisao', 'Rescisão'), ('monitoramento', 'Monitoramento'), ('comercial', 'Comercial')], max_length=50)),
                ('texto', models.TextField()),
                ('palavras_chave', models.CharField(help_text='Separadas por vírgula', max_length=500)),
                ('ativa', models.BooleanField(default=True)),
                ('versao', models.IntegerField(default=1)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('proposta_tecnica', 'Proposta Técnica'), ('proposta_comercial', 'Proposta Comercial')], max_length=50)),
                ('prompt_usado', models.TextField()),
                ('conteudo', models.TextField()),
                ('versao', models.IntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
