# Generated by Django 6.0.2 on 2026-03-05 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0013_alter_contratotarefa_clausula'),
        ('contratos_ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoriaCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_products', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('additional_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lucro', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margem_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorias_calculo', to='contratos.contrato')),
            ],
            options={
                'verbose_name': 'Memória de cálculo',
                'verbose_name_plural': 'Memórias de cálculo',
            },
        ),
        migrations.CreateModel(
            name='MemoriaCalculoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('custo', 'Custo'), ('opex', 'OPEX')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('memoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='contratos_ai.memoriacalculo')),
            ],
        ),
    ]
