# Generated by Django 6.0.2 on 2026-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_epico_tarefa_epico'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='data_inicio_prevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
