# Generated by Django 6.0.2 on 2026-03-04 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_area_campocustomizavelic_centrocusto_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='setor',
        ),
        migrations.DeleteModel(
            name='Setor',
        ),
    ]
