# Generated by Django 6.0.2 on 2026-02-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jira_sync', '0002_jiraproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraconnection',
            name='nome_jira',
            field=models.CharField(blank=True, help_text="Ex: 'descrição da api' (opcional)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jiraconnection',
            name='sufixo_url',
            field=models.CharField(blank=True, help_text='Ex: /rest/api/3 (opcional)', max_length=255, null=True),
        ),
    ]
