# Generated by Django 6.0.2 on 2026-02-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0002_alter_contrato_cliente'),
        ('jira_sync', '0003_jiraconnection_nome_jira_jiraconnection_sufixo_url'),
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jiraproject',
            unique_together={('jira_connection', 'jira_id'), ('jira_connection', 'key')},
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='is_subtask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='issue_type_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='parent_issue',
            field=models.ForeignKey(blank=True, help_text='Issue pai (quando esta issue for subtask)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='jira_sync.jiraissue'),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='parent_key',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jiraissue',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Projeto local (JiraProject) associado a esta issue', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='jira_sync.jiraproject'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['project', 'status'], name='jira_sync_j_project_3c0c97_idx'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['parent_issue'], name='jira_sync_j_parent__be3c31_idx'),
        ),
        migrations.AddIndex(
            model_name='jiraissue',
            index=models.Index(fields=['cliente', 'project', 'is_subtask'], name='jira_sync_j_cliente_e0a34f_idx'),
        ),
    ]
