# Generated by Django 6.0.2 on 2026-02-13 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_alter_contrato_cliente'),
        ('jira_sync', '0004_alter_jiraproject_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiraproject',
            name='contrato',
            field=models.ForeignKey(blank=True, help_text='Contrato do cliente ao qual este projeto Jira está associado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jira_projects', to='contratos.contrato'),
        ),
        migrations.AddIndex(
            model_name='jiraproject',
            index=models.Index(fields=['jira_connection', 'contrato'], name='jira_sync_j_jira_co_de3840_idx'),
        ),
    ]
