# Generated by Django 6.0.2 on 2026-03-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_scripts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='ip_fortigate',
        ),
        migrations.RemoveField(
            model_name='link',
            name='mask',
        ),
        migrations.RemoveField(
            model_name='link',
            name='velocidade_internet',
        ),
        migrations.AddField(
            model_name='link',
            name='designacao_bld',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='ip_bld_fortigate',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='ip_bld_pe',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='ip_lo_pe_bld',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='ip_lo_pe_mpls',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='ip_mpls_fortigate',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='ip_pri_lan_fortigate',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='ip_sec_lan_fortigate',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='loopback_cae',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='loopback_grc',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='loopback_soc',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='mascara_pri_lan',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='mask_mpls',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='mask_sec_lan',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='msk_bld',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='rede_mpls',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='rede_pri_lan',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='rede_sec_lan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='velocidade_bld',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='ip_mpls',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
