# Generated by Django 6.0.2 on 2026-03-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_scripts', '0002_remove_link_ip_fortigate_remove_link_mask_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='tipo',
        ),
        migrations.AddField(
            model_name='link',
            name='designacao_mpls',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
