# Generated by Django 6.0.2 on 2026-03-02 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_scripts', '0003_remove_link_tipo_link_designacao_mpls'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='link',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='velocidade_mpls',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
