# Generated by Django 6.0.2 on 2026-02-25 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userclientemembership_accounts_us_user_id_b1c164_idx'),
        ('clientes', '0002_cliente_logotipo'),
        ('contratos', '0012_contratotarefa_usuario_responsavel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contratos', models.ManyToManyField(blank=True, related_name='equipes', to='contratos.contrato')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_como_gerente', to=settings.AUTH_USER_MODEL)),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_como_lider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EquipeMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('MEMBRO', 'Membro'), ('LIDER', 'Líder'), ('GERENTE', 'Gerente')], default='MEMBRO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='accounts.equipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipes_membro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('INTERNO', 'Interno'), ('CLIENTE', 'Cliente')], default='INTERNO', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='clientes.cliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='equipe',
            index=models.Index(fields=['nome'], name='accounts_eq_nome_5343d5_idx'),
        ),
        migrations.AddIndex(
            model_name='equipemembro',
            index=models.Index(fields=['equipe', 'papel'], name='accounts_eq_equipe__20e343_idx'),
        ),
        migrations.AddIndex(
            model_name='equipemembro',
            index=models.Index(fields=['user', 'ativo'], name='accounts_eq_user_id_a46b98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='equipemembro',
            unique_together={('equipe', 'user')},
        ),
    ]
