# Generated by Django 6.0.2 on 2026-02-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logotipo',
            field=models.ImageField(blank=True, help_text='Imagem do logotipo do cliente (PNG/JPG/SVG)', null=True, upload_to='clientes/logotipos/'),
        ),
    ]
