# Generated by Django 6.0.2 on 2026-03-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cidade_pais_cliente_bairro_cliente_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadefederacao',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UF', to='clientes.pais'),
        ),
    ]
