# Generated by Django 6.0.2 on 2026-03-02 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_logotipo'),
        ('softdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='softdeskchamado',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='softdesk_chamados', to='clientes.cliente'),
        ),
    ]
