# Generated by Django 6.0.2 on 2026-02-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0013_zabbixhost_raw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabbixtrigger',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='zabbixtrigger',
            name='prioridade',
        ),
        migrations.RemoveField(
            model_name='zabbixtrigger',
            name='status',
        ),
        migrations.RemoveField(
            model_name='zabbixtrigger',
            name='ultima_alteracao',
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='enabled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='lastchange',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='severity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zabbixtrigger',
            name='raw',
            field=models.JSONField(null=True),
        ),
    ]
