# Generated by Django 6.0.2 on 2026-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0014_remove_zabbixtrigger_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixtrigger',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='expression',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='priority',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
