# Generated by Django 6.0.2 on 2026-02-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0015_zabbixtrigger_description_zabbixtrigger_expression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixitem',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
