# Generated by Django 6.0.2 on 2026-02-24 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_logotipo'),
        ('zabbix_integration', '0016_zabbixitem_raw'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixSyncControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_full_sync', models.DateTimeField(null=True)),
                ('last_incremental_sync', models.DateTimeField(null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
