# Generated by Django 6.0.2 on 2026-02-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0017_zabbixsynccontrol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zabbixtrigger',
            name='items',
        ),
        migrations.AddField(
            model_name='zabbixtrigger',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='triggers', to='zabbix_integration.zabbixitem'),
        ),
    ]
