# Generated by Django 6.0.2 on 2026-02-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0018_remove_zabbixtrigger_items_zabbixtrigger_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixevent',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
