# Generated by Django 6.0.2 on 2026-02-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0020_alter_zabbixsla_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixsla',
            name='periodo',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zabbixsla',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
