# Generated by Django 6.0.2 on 2026-02-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0021_zabbixsla_periodo_alter_zabbixsla_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixsla',
            name='effective_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zabbixsla',
            name='period',
            field=models.IntegerField(blank=True, choices=[(0, 'daily'), (1, 'weekly'), (2, 'monthly')], null=True),
        ),
    ]
