# Generated by Django 6.0.2 on 2026-02-26 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_logotipo'),
        ('zabbix_integration', '0022_zabbixsla_effective_date_alter_zabbixsla_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixHostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('raw', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'groupid')},
            },
        ),
    ]
