# Generated by Django 6.0.2 on 2026-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0023_zabbixhostgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixhost',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='hosts', to='zabbix_integration.zabbixhostgroup'),
        ),
    ]
