# Generated by Django 6.0.2 on 2026-02-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zabbix_integration', '0024_zabbixhost_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='zabbixevent',
            name='c_eventid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='zabbixevent',
            name='opdata',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='zabbixevent',
            name='r_eventid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
