# Generated by Django 6.0.2 on 2026-02-04 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('parametro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrocliente',
            name='valor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ItensMonitoramento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoramento', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField(blank=True, choices=[('Gráfico', 'Gráfico'), ('Tabela', 'Tabela')], null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitormento', to='clientes.cliente')),
            ],
        ),
    ]
