# Generated by Django 6.0.2 on 2026-02-04 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('parametro', '0002_alter_parametrocliente_valor_itensmonitoramento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itensmonitoramento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitoramento', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='itensmonitoramento',
            name='tipo',
            field=models.TextField(blank=True, choices=[('Grafico', 'Gráfico'), ('Tabela', 'Tabela')], null=True),
        ),
    ]
