# Generated by Django 6.0.2 on 2026-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('proposta', 'Proposta'), ('alerta', 'Alerta'), ('sistema', 'Sistema')], max_length=50),
        ),
    ]
