# Generated by Django 6.0.2 on 2026-02-03 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clientes.cliente'),
        ),
    ]
