# Generated by Django 6.0.2 on 2026-02-19 10:31

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0006_alter_tarefatimer_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoclausula',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
