# Generated by Django 6.0.2 on 2026-02-19 12:25

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_logotipo'),
        ('contratos', '0008_clausula_fts_trigger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopilotActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(max_length=60)),
                ('action_input', models.JSONField()),
                ('action_output', models.JSONField(blank=True, null=True)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopilotRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('QA', 'Pergunta/Resposta'), ('EXTRACT_TASKS', 'Sugerir Tarefas'), ('ACTION', 'Executar Ação')], default='QA', max_length=20)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('ERROR', 'Erro'), ('DENIED', 'Negado')], default='OK', max_length=20)),
                ('user_message', models.TextField()),
                ('query_expansion', models.JSONField(blank=True, null=True)),
                ('retrieved', models.JSONField(blank=True, null=True)),
                ('citations', models.JSONField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=80, null=True)),
                ('prompt_version', models.CharField(blank=True, max_length=40, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('token_usage', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='contratoclausula',
            index=django.contrib.postgres.indexes.GinIndex(fields=['texto'], name='clausula_texto_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='contratoclausula',
            index=django.contrib.postgres.indexes.GinIndex(fields=['titulo'], name='clausula_titulo_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddField(
            model_name='copilotrun',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_runs', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='copilotrun',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_runs', to='contratos.contrato'),
        ),
        migrations.AddField(
            model_name='copilotrun',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copilot_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='copilotactionlog',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='contratos.copilotrun'),
        ),
        migrations.AddIndex(
            model_name='copilotrun',
            index=models.Index(fields=['cliente', 'contrato', 'criado_em'], name='contratos_c_cliente_643332_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotrun',
            index=models.Index(fields=['usuario', 'criado_em'], name='contratos_c_usuario_c001e5_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotrun',
            index=models.Index(fields=['status', 'criado_em'], name='contratos_c_status_3ef626_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotactionlog',
            index=models.Index(fields=['action_name', 'criado_em'], name='contratos_c_action__21a52a_idx'),
        ),
        migrations.AddIndex(
            model_name='copilotactionlog',
            index=models.Index(fields=['ok', 'criado_em'], name='contratos_c_ok_f1510f_idx'),
        ),
    ]
