# Generated by Django 6.0.2 on 2026-03-02 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0012_contratotarefa_usuario_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratotarefa',
            name='clausula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='contratos.contratoclausula'),
        ),
    ]
