# Generated by Django 6.0.2 on 2026-03-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0014_contratotarefa_usuario_criador'),
        ('tarefas', '0002_epico_tarefa_epico'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratotarefa',
            name='epico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrato_tarefas', to='tarefas.epico'),
        ),
    ]
