# Generated by Django 6.0.2 on 2026-03-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0015_contratotarefa_epico'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratotarefa',
            name='data_inicio_prevista',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratotarefa',
            name='horas_previstas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
